### PR TITLE
Fix compiling on Linux 5.0

### PR DESCRIPTION
**Pull request by crawfxrd**
Fix building on Fedora Rawhide (5.0.0-0.rc1.git0.1.fc30.x86_64).

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@crawfxrd With 5.0 landing soon, is this all we need to make it compatible?

**Comment by crawfxrd** [comment]
Don't know. The last build I tried it on was Rawhide 5.0.0-rc6 (they never released a package for rc7?). I'd want to test it on rc8 before merging at this point.

**Comment by Conan-Kudo** [comment]
The compose never succeeded with rc6, so it never left Koji to hit the mirror network. But it was definitely built.

And rc8 looks like it was built recently: https://koji.fedoraproject.org/koji/packageinfo?packageID=8

**Comment by crawfxrd** [comment]
My rawhide hasn't received updates in 2 weeks and that does not seem correct. No changed needed for compiling on kernel-ml 5.0.0-0.rc8 though, and the smoke-tests pass.

```
dattobd: e698cb1
kernel: 5.0.0-0.rc8.git0.1.vanilla.knurd.1.fc30.x86_64
gcc: 9.0.1
bash: 5.0.2(1)-release
python: Python 3.7.2

WARNING: yacc table file version is out of date
test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... skipped 'Broken since 4.17 (see #144)'
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... skipped 'Broken since 4.17 (see #144)'
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... ok
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... ok
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... ok
test_setup_already_tracked_volume (test_setup.TestSetup) ... ok
test_setup_cow_file_on_wrong_device (test_setup.TestSetup) ... ok
test_setup_cow_file_path_is_dir (test_setup.TestSetup) ... ok
test_setup_invalid_minor (test_setup.TestSetup) ... ok
test_setup_readonly_volume (test_setup.TestSetup) ... ok
test_setup_unmounted_volume (test_setup.TestSetup) ... ok
test_setup_volume (test_setup.TestSetup) ... ok
test_setup_volume_path_is_dir (test_setup.TestSetup) ... ok
test_modify_origin (test_snapshot.TestSnapshot) ... ok
test_track_writes (test_snapshot.TestSnapshot) ... ok
test_transition_active_incremental (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_active_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_fs_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_mod_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_nonexistent_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok

----------------------------------------------------------------------
Ran 22 tests in 3.810s

OK (skipped=2)
```

**Pull request merged**
