### PR TITLE
Create sparse file on fallocate failure

### PR DESCRIPTION
**Pull request by dward**
Instead of falling back to writing a large zero'd file, this patch creates a sparse file instead. This will greatly reduce the time it takes to create a snapshot on filesystems that do not support fallocate.

### CODE REVIEW

**Comment by tcaputi** [comment]
Thank you for your contribution. We appreciate any help and input anyone has to offer. However, there is a non-obvious issue with using a sparse file instead of a preallocated file for the COW data. The problem arises from the fact that we do not do COW of the COW file itself. If we did, a single write would cause the system to copy the original data into the COW file, which would then need to be recopied into the COW file forever until the disk runs out of space.

Now lets say we use a sparse file. You have a filesystem with data already on it, you then take the snapshot and the driver begins tracking the changes in the sparse file. Then you DELETE data from the filesystem that existed before the snapshot. On most filesystems, this will simply mark that region as unused, but the data will still remain. The deleted space is now available for the COW file to grow into. If the COW file does grow into that space, we do not perform COW of those blocks of the file, and so they are actually overwritten and the snapshot is corrupted.

That is the reason we use a preallocated file for the COW data. I know that the size of that file can be a pain point for anyone using the driver and I am open to any ideas regarding getting around the issue. Let me know if you can think of anything and feel free to ask questions.

**Comment by dward** [comment]
That makes perfect sense. I'm closing the pull request. Thanks!

**Comment by catphish** [comment]
I am looking into this and I don't fully understand the problem here. In particular, the following sentence confuses me:

> If the COW file does grow into that space, we do not perform COW of those blocks of the file, and so they are actually overwritten and the snapshot is corrupted.

What exactly is being overwritten without COW being performed? Something more important than just deleted data being overwritten by the COW file and not tracked? If it's just deleted data being overwritten by the COW, why does this matter?

I'm sure I'm just missing something, I'd appreciate another attempt to explain the problem. Thanks in advance!

**Comment by tcaputi** [comment]
So the scenario is this:

1. You have a block device with a bunch of files on it
2. You take a snapshot of the block device
3. You delete the files At this point you would expect the snapshot to contain the files, even though they would be gone from the live filesystem.
4. You write a bunch of data to the block device.

This is where the problem arises. If we allow the COW file to grow as needed it may grow into the space of the files that were deleted. This is bad because then our snapshot no longer represents the block device as it existed when we took the snapshot.

The data of the COW file is not itself subject to copy-on-write. If it were writing a single block to the disk would cause an infinite chain of writes to occur. The initial write would cause a write to the cow file, which would be COW'd again into the COW file, which would be COW'd again into the COW file, etc.

This is the reason we need to pre-allocate the file. We need an area of disk that we are sure will exist before and after the snapshot.

**Comment by catphish** [comment]
Thank you, I understand fully now. This seems like it would be very difficult to resolve without filesystem-specific hacks to ensure that the COW files are only created in space that was free at the time the snapshot was taken.

**Pull request closed without merging**
